apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - ingress-workloads
                - key: "karpenter.k8s.aws/instance-family"
                  operator: In
                  values: ["c7a", "c6a", "c5", "c5a", "r7a", "r6a", "r5", "r5a", "r4"]
      containers:
      - name: myapp
        image: nginx
