instance_profile: karpenter-profile-instance
classes:
  - ami: ami-04777
    name: cpu-node-class
pools:
    name: cpu-ondemand
    nodeClass: cpu-node-class
    instCategory: ['"c"']
    instCpu: ["16", "32", "48"]
    instHypervisor: ['"nitro"']
    instGeneration: ['"3"']
    capacityType: ['"on_demand"']
tags: {}
karpenter:
  ami_id: ""
  subnet_selector: ""
  security_group_selector: ""
  instance_category: ""
  instance_profile: ""
  instance_cpu: ""
  capacity_type: ""
  instance_generation: ""
