---
{{- range $pool := .Values.pools }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ $pool.name }}
spec:
  template:
    metadata:
      labels:
        component: {{ $pool.name }}
      annotations: {}
    spec:
      nodeClassRef:
        name: {{ $pool.nodeClass }}
      taints:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: {{ $pool.instCategory }}
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: {{ $pool.instCpu }}
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: {{ $pool.instHypervisor }}
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: {{ $pool.instGeneration }}
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: {{ $pool.capacityType }}
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: Never
    expireAfter: 96h
  limits:
    cpu: "96"
    memory: 10000Gi
  weight: 10
---
{{- end }}
{{- range $class := .Values.classes }}
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ $class.name }}
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        "karpenter.sh/discovery": "testing-private-karpenter.sh"
  securityGroupSelectorTerms:
    - tags:
        "karpenter.sh/discovery": "testing-private-karpenter.sh"
  instanceProfile: {{ $.Values.karpenter.instance_profile }}
  amiSelectorTerms:
    - id: {{ $class.ami }}
{{- if $.Values.tags }}
  tags:
{{- toYaml $.Values.tags | nindent 4 }}
{{- end }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        deleteOnTermination: true
        throughput: 125

  detailedMonitoring: false
---
{{- end }}
