apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  labels:
    environment: development
spec:
  project: default
  source:
    repoURL: https://github.com/AmericaBurger/testing.git
    path: karpenter
    helm:
      valuesObject:
        settings:
          clusterName: {{ .Values.karpenter.cluster_name }}
        serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: {{ .Values.karpenter.role_arn }}
        karpenter:
          subnet_selector: {{ .Values.karpenter.subnet_tag }}
          security_group_selector: {{ .Values.karpenter.security_group_tag }}
          instance_profile: {{ .Values.karpenter.instance_profile }}
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
