apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-defs
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  labels:
    environment: afsafasf
spec:
  project: default
  source:
    repoURL: https://github.com/AmericaBurger/testing.git
    path: karpenter
    helm:
      valuesObject:
        settings:
          clusterName: "testing-eks-cluster"
        serviceAccount:
            name: "karpenter"
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::312713324602:role/karpenter-role"
        karpenter:
          ami_id: '"ami-062ce1f7407168d2f"'
          subnet_selector: '"testing-private-karpenter.sh"'
          security_group_selector: '"testing-private-karpenter.sh"'
          instance_category: ['"c", "r", "m"']
          instance_profile: '"karpenter-instance-profile"'
          instance_cpu: ['"16", "32", "48"']
          capacity_type: '"on_demand"'
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
