apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-defs
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  labels:
    environment: afsafasf
spec:
  project: default
  source:
    repoURL: https://github.com/AmericaBurger/testing.git
    path: karpenter
    helm:
      valuesObject:
        instance_profile: karpenter-profile-instance
        settings:
          clusterName: "testing-eks-cluster"
        serviceAccount:
            name: "karpenter"
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::312713324602:role/karpenter-role"
        karpenter:
          subnet_selector: '"testing-private-karpenter.sh"'
          security_group_selector: '"testing-private-karpenter.sh"'
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
