apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-defs
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  labels:
    environment: afsafasf
spec:
  project: default
  source:
    repoURL: https://github.com/AmericaBurger/testing.git
    path: karpenter
    helm:
      valuesObject:
        karpenter:
          ami_id: '"ami-1234567899999"'
          subnet_selector: '"fasfasdfsad: aafasfasf"'
          security_group_selector: '"fasfasdfsad: aafasfasf"'
          instance_category: ['"c"']
          instance_profile: '"karpenter-profile-instance"'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
