apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-defs
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  labels:
    environment: {{ .Values.common.host }}
spec:
  project: default
  source:
    repoURL: https://github.com/AmericaBurger/testing.git
    path: karpenter-defs
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
