apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-defs
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  labels:
    environment: afsafasf
spec:
  project: default
  source:
    repoURL: https://github.com/AmericaBurger/testing.git
    path: karpenter
    helm:
      valuesObject:
        test: {{ .Values.test }}
        settings:
          clusterName: "testing-eks-cluster"
        serviceAccount:
            name: {{ .Values.serviceAccount.name }}
            annotations:
              eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role_arn }}
        karpenter:
          subnet_selector: '"testing-private-karpenter.sh"'
          security_group_selector: '"testing-private-karpenter.sh"'
          instance_profile: {{ .Values.karpenter.instance_profile }}
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
