apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-defs
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
  labels:
    environment: {{ .Values.common.environment }}
spec:
  project: default
  source:
    repoURL: https://github.com/AmericaBurger/testing.git
    path: karpenter
    helm:
      valuesObject:
        settings:
          clusterName: {{ .Values.karpenter.cluster_name }}
        serviceAccount:
            name: {{ .Values.karpenter.serviceAccount_name }}
            annotations:
              eks.amazonaws.com/role-arn: {{ .Values.karpenter.role_arn }}
        karpenter:
          subnets_ids: {{ .Values.karpenter.subnets_ids }}
          security_group_id: {{ .Values.karpenter.security_group_id }}
          instance_profile: {{ .Values.karpenter.instance_profile }}
          serviceAccount_name: {{ .Values.karpenter.serviceAccount_name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
