{{- range $class := .Values.classes }}
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ $class.name }}
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter: "node-subnet"
        Environment: frodo
  securityGroupSelectorTerms:
    - tags:
        karpenter: "node-sg"
        Environment: frodo
  instanceProfile: {{ $.Values.instanceProfile }}
  amiSelectorTerms:
    - id: {{ $class.ami }}
{{- if $.Values.tags }}
  tags:
{{- toYaml $.Values.tags | nindent 4 }}
{{- end }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        deleteOnTermination: true
        throughput: 125

  detailedMonitoring: false
---
{{- end }}
