---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  user_data: |
    #!/bin/bash
    set -o xtrace
    echo 300 > /proc/sys/net/ipv4/tcp_keepalive_time
    echo 90 > /proc/sys/net/ipv4/tcp_keepalive_probes
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 30Gi
        volumeType: gp3
  instanceProfile: karpenter-controller
  # amiFamily: AL2 # Amazon Linux 2
  amiSelectorTerms:
    - id: {{ .Values.karpenter.ami_id }}
  subnetSelectorTerms:
    - tags:
        {{ .Values.karpenter.subnet_selector}}
  securityGroupSelectorTerms:
    - tags:
        {{ .Values.karpenter.security_group_selector}}